services:
  kotovskaya.order:
    image: seichocorp/kotovskaya-core-orders:latest
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_HTTP_PORTS=8003

  kotovskaya.products:
    image: seichocorp/kotovskaya-core-products:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8004
    ports:
      - "8004:8004"
    restart: always
    env_file:
      - .env

  kotovskaya.categories:
    image: seichocorp/kotovskaya-core-categories:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8001
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env

  kotovskaya.api:
    image: seichocorp/kotovskaya-core-api:latest
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_HTTPS_PORTS=8000
