services:
  kotovskaya.order:
    image: ghcr.io/seicho-group/kotovskaya-orders:latest
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_HTTP_PORTS=8003
      - ASPNETCORE_ENVIRONMENT=Prod

  kotovskaya.products:
    image: ghcr.io/seicho-group/kotovskaya-products:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8004
      - ASPNETCORE_ENVIRONMENT=Prod
    ports:
      - "8004:8004"
    restart: always
    env_file:
      - .env

  kotovskaya.categories:
    image: ghcr.io/seicho-group/kotovskaya-categories:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_ENVIRONMENT=Prod
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env

  kotovskaya.api:
    image: ghcr.io/seicho-group/kotovskaya-api:latest
    ports:
      - "80:8000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8000
      - ASPNETCORE_ENVIRONMENT=Prod
    restart: always
    
networks:
  kotovskaya-network:
    name: kotovskaya-network
    external: true
