services:
  kotovskaya.order:
    image: ghcr.io/seicho-group/kotovskaya-orders:latest
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_HTTP_PORTS=8003
      - ASPNETCORE_ENVIRONMENT=Prod

  kotovskaya.products:
    image: ghcr.io/seicho-group/kotovskaya-products:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8004
      - ASPNETCORE_ENVIRONMENT=Prod
    ports:
      - "8004:8004"
    restart: always
    env_file:
      - .env

  kotovskaya.categories:
    image: ghcr.io/seicho-group/kotovskaya-categories:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_ENVIRONMENT=Prod
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env

  kotovskaya.api:
    image: ghcr.io/seicho-group/kotovskaya-api:latest
    ports:
      - "80:8000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8000
      - ASPNETCORE_ENVIRONMENT=Prod
    restart: always


  kotovskaya.moyskladupdater:
    image: ghcr.io/seicho-group/kotovskaya-moyskladupdater:latest
    build:
      context: .
      dockerfile: Kotovskaya.MoySkladUpdater/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod


  hangfire.server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Kotovskaya123
    ports:
      - "1433:1433"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
      - ${MSSQL_CONFIG_DIR:-./.config/mssql}/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${MSSQL_CONFIG_DIR:-./.config/mssql}/sql/:/usr/src/app/docker-entrypoint-initdb.d

volumes:
  mssqlsystem: # external: true
  mssqluser: # external: true

networks:
  kotovskaya-network:
    name: kotovskaya-network
    external: true
